### ISSUE TITLE
PR하는데 많은 도움이 된 내용들이네요

### ISSUE THREAD

**Issue by milliwonkim** [Minsoo-web/Today-I-Learn#3]
다음 컨텐츠에서 repo를 삭제하는 방법, origin을 삭제하는 방법 등등 다양한 git 관련 터미널 용어들도 정리해주세요!

**Comment by minsoo-web** [comment]
넵 ! cli랑 gui 비교해서 커밋부터 PR. reset 까지 알아보는 것 올려볼려 했는데 repo삭제랑 origin 삭제 및 변경하는 방법도 공부해서 올려보겠습니다! 😄
